version: "3.8"
services:
    # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/entrypoint.sh:/docker/entrypoint.sh
        ports:
            - "5013:8000"
